[package]
authors = ["The Tor Project"]
name = "tor_util"
version = "0.0.1"

[lib]
name = "tor_util"
path = "lib.rs"
crate_type = ["staticlib"]

[dependencies.tor_alloc]
path = "../tor_alloc"
version = "0.0.1"

[dependencies]
libc = "*"

